function T=decision2(X,label,Depth,Splits,MinNode)
T=struct('feature',zeros(2^(Depth-1)-1,1),...
    'threshold',zeros(2^(Depth-1)-1,1),...
    'leaf',zeros(2^(Depth-1),2),...
    'leaf_prob',zeros(2^(Depth-1),1),...
    'depth',Depth);
T=tree_1(1,T,X,label,Depth,Splits,MinNode);